/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GrantedUniverseAuthorityDTOAllOfDto
 */
@JsonPropertyOrder({
  GrantedUniverseAuthorityDTOAllOfDto.JSON_PROPERTY_PERMISSION,
  GrantedUniverseAuthorityDTOAllOfDto.JSON_PROPERTY_UNIVERSE
})
@JsonTypeName("GrantedUniverseAuthorityDTO_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-30T12:56:25.947710400+01:00[Europe/Berlin]")
public class GrantedUniverseAuthorityDTOAllOfDto {
  public static final String JSON_PROPERTY_PERMISSION = "permission";
  private String permission;

  public static final String JSON_PROPERTY_UNIVERSE = "universe";
  private String universe;

  public GrantedUniverseAuthorityDTOAllOfDto() {
  }

  public GrantedUniverseAuthorityDTOAllOfDto permission(String permission) {
    
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPermission() {
    return permission;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermission(String permission) {
    this.permission = permission;
  }


  public GrantedUniverseAuthorityDTOAllOfDto universe(String universe) {
    
    this.universe = universe;
    return this;
  }

   /**
   * Get universe
   * @return universe
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUniverse() {
    return universe;
  }


  @JsonProperty(JSON_PROPERTY_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUniverse(String universe) {
    this.universe = universe;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrantedUniverseAuthorityDTOAllOfDto grantedUniverseAuthorityDTOAllOf = (GrantedUniverseAuthorityDTOAllOfDto) o;
    return Objects.equals(this.permission, grantedUniverseAuthorityDTOAllOf.permission) &&
        Objects.equals(this.universe, grantedUniverseAuthorityDTOAllOf.universe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission, universe);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrantedUniverseAuthorityDTOAllOfDto {\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    universe: ").append(toIndentedString(universe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

