/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetAllItems200ResponseInnerDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ItemRecipeEntryDto
 */
@JsonPropertyOrder({
  ItemRecipeEntryDto.JSON_PROPERTY_AMOUNT_OF_REQUIRED_UNITS,
  ItemRecipeEntryDto.JSON_PROPERTY_ITEM
})
@JsonTypeName("ItemRecipeEntry")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-30T12:56:25.947710400+01:00[Europe/Berlin]")
public class ItemRecipeEntryDto {
  public static final String JSON_PROPERTY_AMOUNT_OF_REQUIRED_UNITS = "amountOfRequiredUnits";
  private Float amountOfRequiredUnits;

  public static final String JSON_PROPERTY_ITEM = "item";
  private GetAllItems200ResponseInnerDto item;

  public ItemRecipeEntryDto() {
  }

  public ItemRecipeEntryDto amountOfRequiredUnits(Float amountOfRequiredUnits) {
    
    this.amountOfRequiredUnits = amountOfRequiredUnits;
    return this;
  }

   /**
   * Get amountOfRequiredUnits
   * @return amountOfRequiredUnits
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_OF_REQUIRED_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAmountOfRequiredUnits() {
    return amountOfRequiredUnits;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_OF_REQUIRED_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountOfRequiredUnits(Float amountOfRequiredUnits) {
    this.amountOfRequiredUnits = amountOfRequiredUnits;
  }


  public ItemRecipeEntryDto item(GetAllItems200ResponseInnerDto item) {
    
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GetAllItems200ResponseInnerDto getItem() {
    return item;
  }


  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItem(GetAllItems200ResponseInnerDto item) {
    this.item = item;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemRecipeEntryDto itemRecipeEntry = (ItemRecipeEntryDto) o;
    return Objects.equals(this.amountOfRequiredUnits, itemRecipeEntry.amountOfRequiredUnits) &&
        Objects.equals(this.item, itemRecipeEntry.item);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountOfRequiredUnits, item);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemRecipeEntryDto {\n");
    sb.append("    amountOfRequiredUnits: ").append(toIndentedString(amountOfRequiredUnits)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

