/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.MaterialDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JewelleryAllOfDto
 */
@JsonPropertyOrder({
  JewelleryAllOfDto.JSON_PROPERTY_MATERIAL,
  JewelleryAllOfDto.JSON_PROPERTY_UPGRADE_SLOTS
})
@JsonTypeName("Jewellery_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-30T12:56:25.947710400+01:00[Europe/Berlin]")
public class JewelleryAllOfDto {
  public static final String JSON_PROPERTY_MATERIAL = "material";
  private MaterialDto material;

  public static final String JSON_PROPERTY_UPGRADE_SLOTS = "upgradeSlots";
  private Integer upgradeSlots;

  public JewelleryAllOfDto() {
  }

  public JewelleryAllOfDto material(MaterialDto material) {
    
    this.material = material;
    return this;
  }

   /**
   * Get material
   * @return material
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MaterialDto getMaterial() {
    return material;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaterial(MaterialDto material) {
    this.material = material;
  }


  public JewelleryAllOfDto upgradeSlots(Integer upgradeSlots) {
    
    this.upgradeSlots = upgradeSlots;
    return this;
  }

   /**
   * Get upgradeSlots
   * @return upgradeSlots
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPGRADE_SLOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUpgradeSlots() {
    return upgradeSlots;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADE_SLOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpgradeSlots(Integer upgradeSlots) {
    this.upgradeSlots = upgradeSlots;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JewelleryAllOfDto jewelleryAllOf = (JewelleryAllOfDto) o;
    return Objects.equals(this.material, jewelleryAllOf.material) &&
        Objects.equals(this.upgradeSlots, jewelleryAllOf.upgradeSlots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(material, upgradeSlots);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JewelleryAllOfDto {\n");
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    upgradeSlots: ").append(toIndentedString(upgradeSlots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

