/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.ItemTypeDto;
import org.openapitools.client.model.MaterialDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JewelleryDto
 */
@JsonPropertyOrder({
  JewelleryDto.JSON_PROPERTY_DESCRIPTION,
  JewelleryDto.JSON_PROPERTY_EFFECT,
  JewelleryDto.JSON_PROPERTY_ID,
  JewelleryDto.JSON_PROPERTY_MAXIMUM_STACK_SIZE,
  JewelleryDto.JSON_PROPERTY_MINIMUM_STACK_SIZE,
  JewelleryDto.JSON_PROPERTY_NAME,
  JewelleryDto.JSON_PROPERTY_NOTE,
  JewelleryDto.JSON_PROPERTY_RARITY,
  JewelleryDto.JSON_PROPERTY_REQUIREMENT,
  JewelleryDto.JSON_PROPERTY_SUBTYPE,
  JewelleryDto.JSON_PROPERTY_TIER,
  JewelleryDto.JSON_PROPERTY_TYPE,
  JewelleryDto.JSON_PROPERTY_VENDOR_PRICE,
  JewelleryDto.JSON_PROPERTY_MATERIAL,
  JewelleryDto.JSON_PROPERTY_UPGRADE_SLOTS
})
@JsonTypeName("Jewellery")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-30T12:56:25.947710400+01:00[Europe/Berlin]")
public class JewelleryDto {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EFFECT = "effect";
  private String effect;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_MAXIMUM_STACK_SIZE = "maximumStackSize";
  private Integer maximumStackSize;

  public static final String JSON_PROPERTY_MINIMUM_STACK_SIZE = "minimumStackSize";
  private Integer minimumStackSize;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NOTE = "note";
  private String note;

  /**
   * Gets or Sets rarity
   */
  public enum RarityEnum {
    UNKNOWN("UNKNOWN"),
    
    COMMON("COMMON"),
    
    RARE("RARE"),
    
    EPIC("EPIC"),
    
    LEGENDARY("LEGENDARY"),
    
    GODLIKE("GODLIKE");

    private String value;

    RarityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RarityEnum fromValue(String value) {
      for (RarityEnum b : RarityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RARITY = "rarity";
  private RarityEnum rarity;

  public static final String JSON_PROPERTY_REQUIREMENT = "requirement";
  private String requirement;

  public static final String JSON_PROPERTY_SUBTYPE = "subtype";
  private ItemTypeDto subtype;

  public static final String JSON_PROPERTY_TIER = "tier";
  private Integer tier;

  public static final String JSON_PROPERTY_TYPE = "type";
  private ItemTypeDto type;

  public static final String JSON_PROPERTY_VENDOR_PRICE = "vendorPrice";
  private Integer vendorPrice;

  public static final String JSON_PROPERTY_MATERIAL = "material";
  private MaterialDto material;

  public static final String JSON_PROPERTY_UPGRADE_SLOTS = "upgradeSlots";
  private Integer upgradeSlots;

  public JewelleryDto() {
  }

  public JewelleryDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public JewelleryDto effect(String effect) {
    
    this.effect = effect;
    return this;
  }

   /**
   * Get effect
   * @return effect
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEffect() {
    return effect;
  }


  @JsonProperty(JSON_PROPERTY_EFFECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEffect(String effect) {
    this.effect = effect;
  }


  public JewelleryDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public JewelleryDto maximumStackSize(Integer maximumStackSize) {
    
    this.maximumStackSize = maximumStackSize;
    return this;
  }

   /**
   * Get maximumStackSize
   * @return maximumStackSize
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAXIMUM_STACK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMaximumStackSize() {
    return maximumStackSize;
  }


  @JsonProperty(JSON_PROPERTY_MAXIMUM_STACK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaximumStackSize(Integer maximumStackSize) {
    this.maximumStackSize = maximumStackSize;
  }


  public JewelleryDto minimumStackSize(Integer minimumStackSize) {
    
    this.minimumStackSize = minimumStackSize;
    return this;
  }

   /**
   * Get minimumStackSize
   * @return minimumStackSize
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MINIMUM_STACK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMinimumStackSize() {
    return minimumStackSize;
  }


  @JsonProperty(JSON_PROPERTY_MINIMUM_STACK_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinimumStackSize(Integer minimumStackSize) {
    this.minimumStackSize = minimumStackSize;
  }


  public JewelleryDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public JewelleryDto note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNote(String note) {
    this.note = note;
  }


  public JewelleryDto rarity(RarityEnum rarity) {
    
    this.rarity = rarity;
    return this;
  }

   /**
   * Get rarity
   * @return rarity
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RARITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RarityEnum getRarity() {
    return rarity;
  }


  @JsonProperty(JSON_PROPERTY_RARITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRarity(RarityEnum rarity) {
    this.rarity = rarity;
  }


  public JewelleryDto requirement(String requirement) {
    
    this.requirement = requirement;
    return this;
  }

   /**
   * Get requirement
   * @return requirement
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRequirement() {
    return requirement;
  }


  @JsonProperty(JSON_PROPERTY_REQUIREMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequirement(String requirement) {
    this.requirement = requirement;
  }


  public JewelleryDto subtype(ItemTypeDto subtype) {
    
    this.subtype = subtype;
    return this;
  }

   /**
   * Get subtype
   * @return subtype
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemTypeDto getSubtype() {
    return subtype;
  }


  @JsonProperty(JSON_PROPERTY_SUBTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubtype(ItemTypeDto subtype) {
    this.subtype = subtype;
  }


  public JewelleryDto tier(Integer tier) {
    
    this.tier = tier;
    return this;
  }

   /**
   * Get tier
   * @return tier
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTier() {
    return tier;
  }


  @JsonProperty(JSON_PROPERTY_TIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTier(Integer tier) {
    this.tier = tier;
  }


  public JewelleryDto type(ItemTypeDto type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemTypeDto getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(ItemTypeDto type) {
    this.type = type;
  }


  public JewelleryDto vendorPrice(Integer vendorPrice) {
    
    this.vendorPrice = vendorPrice;
    return this;
  }

   /**
   * Get vendorPrice
   * @return vendorPrice
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VENDOR_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVendorPrice() {
    return vendorPrice;
  }


  @JsonProperty(JSON_PROPERTY_VENDOR_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVendorPrice(Integer vendorPrice) {
    this.vendorPrice = vendorPrice;
  }


  public JewelleryDto material(MaterialDto material) {
    
    this.material = material;
    return this;
  }

   /**
   * Get material
   * @return material
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MaterialDto getMaterial() {
    return material;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaterial(MaterialDto material) {
    this.material = material;
  }


  public JewelleryDto upgradeSlots(Integer upgradeSlots) {
    
    this.upgradeSlots = upgradeSlots;
    return this;
  }

   /**
   * Get upgradeSlots
   * @return upgradeSlots
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPGRADE_SLOTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getUpgradeSlots() {
    return upgradeSlots;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADE_SLOTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpgradeSlots(Integer upgradeSlots) {
    this.upgradeSlots = upgradeSlots;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JewelleryDto jewellery = (JewelleryDto) o;
    return Objects.equals(this.description, jewellery.description) &&
        Objects.equals(this.effect, jewellery.effect) &&
        Objects.equals(this.id, jewellery.id) &&
        Objects.equals(this.maximumStackSize, jewellery.maximumStackSize) &&
        Objects.equals(this.minimumStackSize, jewellery.minimumStackSize) &&
        Objects.equals(this.name, jewellery.name) &&
        Objects.equals(this.note, jewellery.note) &&
        Objects.equals(this.rarity, jewellery.rarity) &&
        Objects.equals(this.requirement, jewellery.requirement) &&
        Objects.equals(this.subtype, jewellery.subtype) &&
        Objects.equals(this.tier, jewellery.tier) &&
        Objects.equals(this.type, jewellery.type) &&
        Objects.equals(this.vendorPrice, jewellery.vendorPrice) &&
        Objects.equals(this.material, jewellery.material) &&
        Objects.equals(this.upgradeSlots, jewellery.upgradeSlots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, effect, id, maximumStackSize, minimumStackSize, name, note, rarity, requirement, subtype, tier, type, vendorPrice, material, upgradeSlots);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JewelleryDto {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    effect: ").append(toIndentedString(effect)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maximumStackSize: ").append(toIndentedString(maximumStackSize)).append("\n");
    sb.append("    minimumStackSize: ").append(toIndentedString(minimumStackSize)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    rarity: ").append(toIndentedString(rarity)).append("\n");
    sb.append("    requirement: ").append(toIndentedString(requirement)).append("\n");
    sb.append("    subtype: ").append(toIndentedString(subtype)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vendorPrice: ").append(toIndentedString(vendorPrice)).append("\n");
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    upgradeSlots: ").append(toIndentedString(upgradeSlots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

