/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.PrimaryAttributeDto;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TalentDto
 */
@JsonPropertyOrder({
  TalentDto.JSON_PROPERTY_FIRST_ATTRIBUTE,
  TalentDto.JSON_PROPERTY_GROUP,
  TalentDto.JSON_PROPERTY_ID,
  TalentDto.JSON_PROPERTY_NAME,
  TalentDto.JSON_PROPERTY_SECOND_ATTRIBUTE,
  TalentDto.JSON_PROPERTY_THIRD_ATTRIBUTE
})
@JsonTypeName("Talent")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-30T12:56:25.947710400+01:00[Europe/Berlin]")
public class TalentDto {
  public static final String JSON_PROPERTY_FIRST_ATTRIBUTE = "firstAttribute";
  private PrimaryAttributeDto firstAttribute;

  public static final String JSON_PROPERTY_GROUP = "group";
  private String group;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_SECOND_ATTRIBUTE = "secondAttribute";
  private PrimaryAttributeDto secondAttribute;

  public static final String JSON_PROPERTY_THIRD_ATTRIBUTE = "thirdAttribute";
  private PrimaryAttributeDto thirdAttribute;

  public TalentDto() {
  }

  public TalentDto firstAttribute(PrimaryAttributeDto firstAttribute) {
    
    this.firstAttribute = firstAttribute;
    return this;
  }

   /**
   * Get firstAttribute
   * @return firstAttribute
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRST_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PrimaryAttributeDto getFirstAttribute() {
    return firstAttribute;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstAttribute(PrimaryAttributeDto firstAttribute) {
    this.firstAttribute = firstAttribute;
  }


  public TalentDto group(String group) {
    
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGroup() {
    return group;
  }


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroup(String group) {
    this.group = group;
  }


  public TalentDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public TalentDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public TalentDto secondAttribute(PrimaryAttributeDto secondAttribute) {
    
    this.secondAttribute = secondAttribute;
    return this;
  }

   /**
   * Get secondAttribute
   * @return secondAttribute
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECOND_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PrimaryAttributeDto getSecondAttribute() {
    return secondAttribute;
  }


  @JsonProperty(JSON_PROPERTY_SECOND_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecondAttribute(PrimaryAttributeDto secondAttribute) {
    this.secondAttribute = secondAttribute;
  }


  public TalentDto thirdAttribute(PrimaryAttributeDto thirdAttribute) {
    
    this.thirdAttribute = thirdAttribute;
    return this;
  }

   /**
   * Get thirdAttribute
   * @return thirdAttribute
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_THIRD_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PrimaryAttributeDto getThirdAttribute() {
    return thirdAttribute;
  }


  @JsonProperty(JSON_PROPERTY_THIRD_ATTRIBUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThirdAttribute(PrimaryAttributeDto thirdAttribute) {
    this.thirdAttribute = thirdAttribute;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TalentDto talent = (TalentDto) o;
    return Objects.equals(this.firstAttribute, talent.firstAttribute) &&
        Objects.equals(this.group, talent.group) &&
        Objects.equals(this.id, talent.id) &&
        Objects.equals(this.name, talent.name) &&
        Objects.equals(this.secondAttribute, talent.secondAttribute) &&
        Objects.equals(this.thirdAttribute, talent.thirdAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstAttribute, group, id, name, secondAttribute, thirdAttribute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TalentDto {\n");
    sb.append("    firstAttribute: ").append(toIndentedString(firstAttribute)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    secondAttribute: ").append(toIndentedString(secondAttribute)).append("\n");
    sb.append("    thirdAttribute: ").append(toIndentedString(thirdAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

