/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AdditiveUpgradeEffectAllOfDto
 */
class AdditiveUpgradeEffectAllOfDtoTest {
    private final AdditiveUpgradeEffectAllOfDto model = new AdditiveUpgradeEffectAllOfDto();

    /**
     * Model tests for AdditiveUpgradeEffectAllOfDto
     */
    @Test
    void testAdditiveUpgradeEffectAllOfDto() {
        // TODO: test AdditiveUpgradeEffectAllOfDto
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

}
