/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.MaterialDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ArmorAllOfDto
 */
class ArmorAllOfDtoTest {
    private final ArmorAllOfDto model = new ArmorAllOfDto();

    /**
     * Model tests for ArmorAllOfDto
     */
    @Test
    void testArmorAllOfDto() {
        // TODO: test ArmorAllOfDto
    }

    /**
     * Test the property 'armor'
     */
    @Test
    void armorTest() {
        // TODO: test armor
    }

    /**
     * Test the property 'material'
     */
    @Test
    void materialTest() {
        // TODO: test material
    }

    /**
     * Test the property 'upgradeSlots'
     */
    @Test
    void upgradeSlotsTest() {
        // TODO: test upgradeSlots
    }

    /**
     * Test the property 'weight'
     */
    @Test
    void weightTest() {
        // TODO: test weight
    }

}
