/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CraftingRecipeMaterialsInnerDto;
import org.openapitools.client.model.ItemRecipeEntryDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CraftingRecipeDto
 */
class CraftingRecipeDtoTest {
    private final CraftingRecipeDto model = new CraftingRecipeDto();

    /**
     * Model tests for CraftingRecipeDto
     */
    @Test
    void testCraftingRecipeDto() {
        // TODO: test CraftingRecipeDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'materials'
     */
    @Test
    void materialsTest() {
        // TODO: test materials
    }

    /**
     * Test the property 'otherCircumstances'
     */
    @Test
    void otherCircumstancesTest() {
        // TODO: test otherCircumstances
    }

    /**
     * Test the property 'product'
     */
    @Test
    void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'profession'
     */
    @Test
    void professionTest() {
        // TODO: test profession
    }

    /**
     * Test the property 'requirement'
     */
    @Test
    void requirementTest() {
        // TODO: test requirement
    }

    /**
     * Test the property 'sideProduct'
     */
    @Test
    void sideProductTest() {
        // TODO: test sideProduct
    }

}
