/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetAllItems200ResponseInnerDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ItemRecipeEntryAllOfDto
 */
class ItemRecipeEntryAllOfDtoTest {
    private final ItemRecipeEntryAllOfDto model = new ItemRecipeEntryAllOfDto();

    /**
     * Model tests for ItemRecipeEntryAllOfDto
     */
    @Test
    void testItemRecipeEntryAllOfDto() {
        // TODO: test ItemRecipeEntryAllOfDto
    }

    /**
     * Test the property 'amountOfRequiredUnits'
     */
    @Test
    void amountOfRequiredUnitsTest() {
        // TODO: test amountOfRequiredUnits
    }

    /**
     * Test the property 'item'
     */
    @Test
    void itemTest() {
        // TODO: test item
    }

}
