/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.ItemTypeDto;
import org.openapitools.client.model.MaterialDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShieldDto
 */
class ShieldDtoTest {
    private final ShieldDto model = new ShieldDto();

    /**
     * Model tests for ShieldDto
     */
    @Test
    void testShieldDto() {
        // TODO: test ShieldDto
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'effect'
     */
    @Test
    void effectTest() {
        // TODO: test effect
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'maximumStackSize'
     */
    @Test
    void maximumStackSizeTest() {
        // TODO: test maximumStackSize
    }

    /**
     * Test the property 'minimumStackSize'
     */
    @Test
    void minimumStackSizeTest() {
        // TODO: test minimumStackSize
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'note'
     */
    @Test
    void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'rarity'
     */
    @Test
    void rarityTest() {
        // TODO: test rarity
    }

    /**
     * Test the property 'requirement'
     */
    @Test
    void requirementTest() {
        // TODO: test requirement
    }

    /**
     * Test the property 'subtype'
     */
    @Test
    void subtypeTest() {
        // TODO: test subtype
    }

    /**
     * Test the property 'tier'
     */
    @Test
    void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'vendorPrice'
     */
    @Test
    void vendorPriceTest() {
        // TODO: test vendorPrice
    }

    /**
     * Test the property 'armor'
     */
    @Test
    void armorTest() {
        // TODO: test armor
    }

    /**
     * Test the property 'hit'
     */
    @Test
    void hitTest() {
        // TODO: test hit
    }

    /**
     * Test the property 'initiative'
     */
    @Test
    void initiativeTest() {
        // TODO: test initiative
    }

    /**
     * Test the property 'material'
     */
    @Test
    void materialTest() {
        // TODO: test material
    }

    /**
     * Test the property 'upgradeSlots'
     */
    @Test
    void upgradeSlotsTest() {
        // TODO: test upgradeSlots
    }

    /**
     * Test the property 'weight'
     */
    @Test
    void weightTest() {
        // TODO: test weight
    }

}
