/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.PrimaryAttributeDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TalentDto
 */
class TalentDtoTest {
    private final TalentDto model = new TalentDto();

    /**
     * Model tests for TalentDto
     */
    @Test
    void testTalentDto() {
        // TODO: test TalentDto
    }

    /**
     * Test the property 'firstAttribute'
     */
    @Test
    void firstAttributeTest() {
        // TODO: test firstAttribute
    }

    /**
     * Test the property 'group'
     */
    @Test
    void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'secondAttribute'
     */
    @Test
    void secondAttributeTest() {
        // TODO: test secondAttribute
    }

    /**
     * Test the property 'thirdAttribute'
     */
    @Test
    void thirdAttributeTest() {
        // TODO: test thirdAttribute
    }

}
