/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpgradeEffectDto
 */
class UpgradeEffectDtoTest {
    private final UpgradeEffectDto model = new UpgradeEffectDto();

    /**
     * Model tests for UpgradeEffectDto
     */
    @Test
    void testUpgradeEffectDto() {
        // TODO: test UpgradeEffectDto
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'upgradeManipulator'
     */
    @Test
    void upgradeManipulatorTest() {
        // TODO: test upgradeManipulator
    }

}
