/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.MaterialDto;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WeaponAllOfDto
 */
class WeaponAllOfDtoTest {
    private final WeaponAllOfDto model = new WeaponAllOfDto();

    /**
     * Model tests for WeaponAllOfDto
     */
    @Test
    void testWeaponAllOfDto() {
        // TODO: test WeaponAllOfDto
    }

    /**
     * Test the property 'damage'
     */
    @Test
    void damageTest() {
        // TODO: test damage
    }

    /**
     * Test the property 'dice'
     */
    @Test
    void diceTest() {
        // TODO: test dice
    }

    /**
     * Test the property 'hit'
     */
    @Test
    void hitTest() {
        // TODO: test hit
    }

    /**
     * Test the property 'initiative'
     */
    @Test
    void initiativeTest() {
        // TODO: test initiative
    }

    /**
     * Test the property 'material'
     */
    @Test
    void materialTest() {
        // TODO: test material
    }

    /**
     * Test the property 'upgradeSlots'
     */
    @Test
    void upgradeSlotsTest() {
        // TODO: test upgradeSlots
    }

}
