/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ExportBackupParams,
  ImportBackupParams,
  StreamingResponseBody
} from '.././model';





/**
 * @summary Creates a backup of the nexus
 */
export const exportBackup = (
    params?: ExportBackupParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StreamingResponseBody>> => {
    
    
    return axios.get(
      `/api/backup/export`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getExportBackupQueryKey = (params?: ExportBackupParams,) => {
    return [
    `/api/backup/export`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getExportBackupQueryOptions = <TData = Awaited<ReturnType<typeof exportBackup>>, TError = AxiosError<unknown>>(params?: ExportBackupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportBackupQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportBackup>>> = ({ signal }) => exportBackup(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportBackupQueryResult = NonNullable<Awaited<ReturnType<typeof exportBackup>>>
export type ExportBackupQueryError = AxiosError<unknown>


export function useExportBackup<TData = Awaited<ReturnType<typeof exportBackup>>, TError = AxiosError<unknown>>(
 params: undefined |  ExportBackupParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportBackup>>,
          TError,
          Awaited<ReturnType<typeof exportBackup>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportBackup<TData = Awaited<ReturnType<typeof exportBackup>>, TError = AxiosError<unknown>>(
 params?: ExportBackupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportBackup>>,
          TError,
          Awaited<ReturnType<typeof exportBackup>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportBackup<TData = Awaited<ReturnType<typeof exportBackup>>, TError = AxiosError<unknown>>(
 params?: ExportBackupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Creates a backup of the nexus
 */

export function useExportBackup<TData = Awaited<ReturnType<typeof exportBackup>>, TError = AxiosError<unknown>>(
 params?: ExportBackupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackup>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportBackupQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Import a backup to the nexus
 */
export const importBackup = (
    params: ImportBackupParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/backup/import`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getImportBackupMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBackup>>, TError,{params: ImportBackupParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof importBackup>>, TError,{params: ImportBackupParams}, TContext> => {

const mutationKey = ['importBackup'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importBackup>>, {params: ImportBackupParams}> = (props) => {
          const {params} = props ?? {};

          return  importBackup(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportBackupMutationResult = NonNullable<Awaited<ReturnType<typeof importBackup>>>
    
    export type ImportBackupMutationError = AxiosError<unknown>

    /**
 * @summary Import a backup to the nexus
 */
export const useImportBackup = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBackup>>, TError,{params: ImportBackupParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importBackup>>,
        TError,
        {params: ImportBackupParams},
        TContext
      > => {

      const mutationOptions = getImportBackupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    