/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddUniversePermissionParams,
  RemoveUniversePermissionParams,
  Universe,
  UserDatabaseObjectPermissionDTO
} from '.././model';





/**
 * @summary Get all Universes
 */
export const getAllUniverses = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Universe[]>> => {
    
    
    return axios.get(
      `/api/universes`,options
    );
  }




export const getGetAllUniversesQueryKey = () => {
    return [
    `/api/universes`
    ] as const;
    }

    
export const getGetAllUniversesQueryOptions = <TData = Awaited<ReturnType<typeof getAllUniverses>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUniversesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUniverses>>> = ({ signal }) => getAllUniverses({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUniversesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUniverses>>>
export type GetAllUniversesQueryError = AxiosError<unknown>


export function useGetAllUniverses<TData = Awaited<ReturnType<typeof getAllUniverses>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUniverses>>,
          TError,
          Awaited<ReturnType<typeof getAllUniverses>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUniverses<TData = Awaited<ReturnType<typeof getAllUniverses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUniverses>>,
          TError,
          Awaited<ReturnType<typeof getAllUniverses>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUniverses<TData = Awaited<ReturnType<typeof getAllUniverses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Universes
 */

export function useGetAllUniverses<TData = Awaited<ReturnType<typeof getAllUniverses>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUniverses>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUniversesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create a universe
 */
export const createUniverse = (
    universe: Universe, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Universe>> => {
    
    
    return axios.post(
      `/api/universes`,
      universe,options
    );
  }



export const getCreateUniverseMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniverse>>, TError,{data: Universe}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createUniverse>>, TError,{data: Universe}, TContext> => {

const mutationKey = ['createUniverse'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUniverse>>, {data: Universe}> = (props) => {
          const {data} = props ?? {};

          return  createUniverse(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUniverseMutationResult = NonNullable<Awaited<ReturnType<typeof createUniverse>>>
    export type CreateUniverseMutationBody = Universe
    export type CreateUniverseMutationError = AxiosError<unknown>

    /**
 * @summary Create a universe
 */
export const useCreateUniverse = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniverse>>, TError,{data: Universe}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUniverse>>,
        TError,
        {data: Universe},
        TContext
      > => {

      const mutationOptions = getCreateUniverseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update a universe
 */
export const updateUniverse = (
    universeId: string,
    universe: Universe, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Universe>> => {
    
    
    return axios.put(
      `/api/universes/${universeId}`,
      universe,options
    );
  }



export const getUpdateUniverseMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniverse>>, TError,{universeId: string;data: Universe}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUniverse>>, TError,{universeId: string;data: Universe}, TContext> => {

const mutationKey = ['updateUniverse'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUniverse>>, {universeId: string;data: Universe}> = (props) => {
          const {universeId,data} = props ?? {};

          return  updateUniverse(universeId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUniverseMutationResult = NonNullable<Awaited<ReturnType<typeof updateUniverse>>>
    export type UpdateUniverseMutationBody = Universe
    export type UpdateUniverseMutationError = AxiosError<unknown>

    /**
 * @summary Update a universe
 */
export const useUpdateUniverse = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniverse>>, TError,{universeId: string;data: Universe}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUniverse>>,
        TError,
        {universeId: string;data: Universe},
        TContext
      > => {

      const mutationOptions = getUpdateUniverseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a universe
 */
export const deleteUniverse = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/universes/${universe}`,options
    );
  }



export const getDeleteUniverseMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniverse>>, TError,{universe: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUniverse>>, TError,{universe: string}, TContext> => {

const mutationKey = ['deleteUniverse'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUniverse>>, {universe: string}> = (props) => {
          const {universe} = props ?? {};

          return  deleteUniverse(universe,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUniverseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUniverse>>>
    
    export type DeleteUniverseMutationError = AxiosError<unknown>

    /**
 * @summary Delete a universe
 */
export const useDeleteUniverse = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniverse>>, TError,{universe: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUniverse>>,
        TError,
        {universe: string},
        TContext
      > => {

      const mutationOptions = getDeleteUniverseMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get a universe
 */
export const getUniverse = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Universe>> => {
    
    
    return axios.get(
      `/api/universes/${universe}`,options
    );
  }




export const getGetUniverseQueryKey = (universe?: string,) => {
    return [
    `/api/universes/${universe}`
    ] as const;
    }

    
export const getGetUniverseQueryOptions = <TData = Awaited<ReturnType<typeof getUniverse>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUniverseQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUniverse>>> = ({ signal }) => getUniverse(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUniverseQueryResult = NonNullable<Awaited<ReturnType<typeof getUniverse>>>
export type GetUniverseQueryError = AxiosError<unknown>


export function useGetUniverse<TData = Awaited<ReturnType<typeof getUniverse>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniverse>>,
          TError,
          Awaited<ReturnType<typeof getUniverse>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniverse<TData = Awaited<ReturnType<typeof getUniverse>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniverse>>,
          TError,
          Awaited<ReturnType<typeof getUniverse>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniverse<TData = Awaited<ReturnType<typeof getUniverse>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a universe
 */

export function useGetUniverse<TData = Awaited<ReturnType<typeof getUniverse>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniverse>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUniverseQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Removes all access rights to the universe from the given user
 */
export const removeUniversePermission = (
    universe: string,
    params: RemoveUniversePermissionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/universes/${universe}/permission`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getRemoveUniversePermissionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUniversePermission>>, TError,{universe: string;params: RemoveUniversePermissionParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeUniversePermission>>, TError,{universe: string;params: RemoveUniversePermissionParams}, TContext> => {

const mutationKey = ['removeUniversePermission'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeUniversePermission>>, {universe: string;params: RemoveUniversePermissionParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  removeUniversePermission(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveUniversePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof removeUniversePermission>>>
    
    export type RemoveUniversePermissionMutationError = AxiosError<unknown>

    /**
 * @summary Removes all access rights to the universe from the given user
 */
export const useRemoveUniversePermission = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUniversePermission>>, TError,{universe: string;params: RemoveUniversePermissionParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeUniversePermission>>,
        TError,
        {universe: string;params: RemoveUniversePermissionParams},
        TContext
      > => {

      const mutationOptions = getRemoveUniversePermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List all access rights of the universe
 */
export const getUniversePermissions = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDatabaseObjectPermissionDTO[]>> => {
    
    
    return axios.get(
      `/api/universes/${universe}/permission`,options
    );
  }




export const getGetUniversePermissionsQueryKey = (universe?: string,) => {
    return [
    `/api/universes/${universe}/permission`
    ] as const;
    }

    
export const getGetUniversePermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getUniversePermissions>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUniversePermissionsQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUniversePermissions>>> = ({ signal }) => getUniversePermissions(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUniversePermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUniversePermissions>>>
export type GetUniversePermissionsQueryError = AxiosError<unknown>


export function useGetUniversePermissions<TData = Awaited<ReturnType<typeof getUniversePermissions>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversePermissions>>,
          TError,
          Awaited<ReturnType<typeof getUniversePermissions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversePermissions<TData = Awaited<ReturnType<typeof getUniversePermissions>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversePermissions>>,
          TError,
          Awaited<ReturnType<typeof getUniversePermissions>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversePermissions<TData = Awaited<ReturnType<typeof getUniversePermissions>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all access rights of the universe
 */

export function useGetUniversePermissions<TData = Awaited<ReturnType<typeof getUniversePermissions>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversePermissions>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUniversePermissionsQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add the given access right to the given user
 */
export const addUniversePermission = (
    universe: string,
    params: AddUniversePermissionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/universes/${universe}/permission`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getAddUniversePermissionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUniversePermission>>, TError,{universe: string;params: AddUniversePermissionParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addUniversePermission>>, TError,{universe: string;params: AddUniversePermissionParams}, TContext> => {

const mutationKey = ['addUniversePermission'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addUniversePermission>>, {universe: string;params: AddUniversePermissionParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  addUniversePermission(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddUniversePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof addUniversePermission>>>
    
    export type AddUniversePermissionMutationError = AxiosError<unknown>

    /**
 * @summary Add the given access right to the given user
 */
export const useAddUniversePermission = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUniversePermission>>, TError,{universe: string;params: AddUniversePermissionParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addUniversePermission>>,
        TError,
        {universe: string;params: AddUniversePermissionParams},
        TContext
      > => {

      const mutationOptions = getAddUniversePermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    