/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemStackItem } from './itemStackItem';
import type { ArmorEquipmentAllOf } from './armorEquipmentAllOf';

export type ArmorEquipment = ItemStackItem & ArmorEquipmentAllOf;
