/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EArmorSlot } from './eArmorSlot';
import type { Armor } from './armor';

export type ArmorEquipmentAllOf = {
  armor?: number;
  armorSlot?: EArmorSlot;
  item?: Armor;
  maxArmor?: number;
  maxDurability?: number;
  maxProtection?: number;
  protection?: number;
  relativeDurability?: number;
  wear?: number;
  weight?: number;
};
