/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CalculationRequestConstants } from './calculationRequestConstants';

export interface CalculationRequest {
  constants?: CalculationRequestConstants;
  formulas?: string[];
}
