/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CharacterStatsDtoPrimaryStats } from './characterStatsDtoPrimaryStats';
import type { CharacterStatsDtoSecondaryStats } from './characterStatsDtoSecondaryStats';

export interface CharacterStatsDto {
  primaryStats: CharacterStatsDtoPrimaryStats;
  secondaryStats: CharacterStatsDtoSecondaryStats;
}
