/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Inventory } from './inventory';

export interface CharacterInventory {
  coin?: number;
  inventory?: Inventory;
}
