/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CharacterSettingsDto {
  maxPrimaryAttributeSum?: number;
  maxPrimaryAttributeValue?: number;
  minPrimaryAttributeValue?: number;
  talentPointFormula: string;
  tierFormula: string;
}
