/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CharacterLevel {
  experience?: number;
  level?: number;
  skillPoints?: number;
}
