/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemStackItem } from './itemStackItem';
import type { ArmorEquipment } from './armorEquipment';
import type { JewelleryEquipment } from './jewelleryEquipment';
import type { ShieldEquipment } from './shieldEquipment';
import type { WeaponEquipment } from './weaponEquipment';

export type InventoryRemoveRequestItemStack = ItemStackItem | ArmorEquipment | JewelleryEquipment | ShieldEquipment | WeaponEquipment;
