/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Item } from './item';

export type ItemUsageAllOf = {
  amount?: number;
  resource?: Item;
};
