/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ItemStackItem } from './itemStackItem';
import type { JewelleryEquipmentAllOf } from './jewelleryEquipmentAllOf';

export type JewelleryEquipment = ItemStackItem & JewelleryEquipmentAllOf;
