/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IResourceUsageObject } from './iResourceUsageObject';
import type { MaterialUsageAllOf } from './materialUsageAllOf';

export type MaterialUsage = IResourceUsageObject & MaterialUsageAllOf & Required<Pick<IResourceUsageObject & MaterialUsageAllOf, 'resource'>>;
