/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PrimaryStatTrait } from './primaryStatTrait';
import type { SecondaryStatTrait } from './secondaryStatTrait';
import type { SimpleCharacterTrait } from './simpleCharacterTrait';
import type { TalentCharacterTrait } from './talentCharacterTrait';

export type NationDisadvantageTraitsItem = PrimaryStatTrait | SecondaryStatTrait | SimpleCharacterTrait | TalentCharacterTrait;
