/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ICharacterTrait } from './iCharacterTrait';
import type { PrimaryStatTraitAllOf } from './primaryStatTraitAllOf';

export type PrimaryStatTrait = ICharacterTrait & PrimaryStatTraitAllOf & Required<Pick<ICharacterTrait & PrimaryStatTraitAllOf, 'attribute' | 'calculation' | 'description'>>;
