/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Shield } from './shield';

export type ShieldEquipmentAllOf = {
  armor?: number;
  hit?: number;
  initiative?: number;
  item?: Shield;
  maxArmor?: number;
  maxDurability?: number;
  maxProtection?: number;
  protection?: number;
  relativeDurability?: number;
  wear?: number;
  weight?: number;
};
