/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ICharacterTrait } from './iCharacterTrait';

export type SimpleCharacterTrait = ICharacterTrait & Required<Pick<ICharacterTrait, 'description'>>;
