/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TagCast } from './tagCast';
import type { TalentCast } from './talentCast';

export type SpellCast = TagCast | TalentCast;
