/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ISpellCast } from './iSpellCast';
import type { TagCastAllOf } from './tagCastAllOf';

export type TagCast = ISpellCast & TagCastAllOf & Required<Pick<ISpellCast & TagCastAllOf, 'tagRequirement'>>;
