/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpgradeRequestItemStackItem } from './upgradeRequestItemStackItem';
import type { Upgrade } from './upgrade';

export interface UpgradeRequestItemStack {
  item: UpgradeRequestItemStackItem;
  upgrade: Upgrade;
}
