/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CharacterResourceUsage } from './characterResourceUsage';
import type { ItemUsage } from './itemUsage';
import type { MaterialUsage } from './materialUsage';

export type UpgradeRecipeMaterialsItem = CharacterResourceUsage | ItemUsage | MaterialUsage;
