/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IBinaryExpressionTreeNode } from './iBinaryExpressionTreeNode';
import type { VariableNodeAllOf } from './variableNodeAllOf';

export type VariableNode = IBinaryExpressionTreeNode & VariableNodeAllOf;
