/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CraftingRecipe,
  DeleteAllCraftingRecipesParams,
  GetAllCraftingRecipesParams
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllCraftingRecipes = (
    universe: string,
    params: DeleteAllCraftingRecipesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/crafting-recipes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllCraftingRecipesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllCraftingRecipes>>, TError,{universe: string;params: DeleteAllCraftingRecipesParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllCraftingRecipes>>, TError,{universe: string;params: DeleteAllCraftingRecipesParams}, TContext> => {

const mutationKey = ['deleteAllCraftingRecipes'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllCraftingRecipes>>, {universe: string;params: DeleteAllCraftingRecipesParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllCraftingRecipes(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllCraftingRecipesMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllCraftingRecipes>>>
    
    export type DeleteAllCraftingRecipesMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllCraftingRecipes = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllCraftingRecipes>>, TError,{universe: string;params: DeleteAllCraftingRecipesParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllCraftingRecipes>>,
        TError,
        {universe: string;params: DeleteAllCraftingRecipesParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllCraftingRecipesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all objects from the database
 */
export const getAllCraftingRecipes = (
    universe: string,
    params?: GetAllCraftingRecipesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CraftingRecipe[]>> => {
    
    
    return axios.get(
      `/api/${universe}/crafting-recipes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllCraftingRecipesQueryKey = (universe?: string,
    params?: GetAllCraftingRecipesParams,) => {
    return [
    `/api/${universe}/crafting-recipes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllCraftingRecipesQueryOptions = <TData = Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError = AxiosError<unknown>>(universe: string,
    params?: GetAllCraftingRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCraftingRecipesQueryKey(universe,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCraftingRecipes>>> = ({ signal }) => getAllCraftingRecipes(universe,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCraftingRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCraftingRecipes>>>
export type GetAllCraftingRecipesQueryError = AxiosError<unknown>


export function useGetAllCraftingRecipes<TData = Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError = AxiosError<unknown>>(
 universe: string,
    params: undefined |  GetAllCraftingRecipesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCraftingRecipes>>,
          TError,
          Awaited<ReturnType<typeof getAllCraftingRecipes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCraftingRecipes<TData = Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllCraftingRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCraftingRecipes>>,
          TError,
          Awaited<ReturnType<typeof getAllCraftingRecipes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCraftingRecipes<TData = Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllCraftingRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all objects from the database
 */

export function useGetAllCraftingRecipes<TData = Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllCraftingRecipesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCraftingRecipes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCraftingRecipesQueryOptions(universe,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllCraftingRecipes = (
    universe: string,
    craftingRecipe: CraftingRecipe[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CraftingRecipe[]>> => {
    
    
    return axios.post(
      `/api/${universe}/crafting-recipes`,
      craftingRecipe,options
    );
  }



export const getInsertAllCraftingRecipesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllCraftingRecipes>>, TError,{universe: string;data: CraftingRecipe[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllCraftingRecipes>>, TError,{universe: string;data: CraftingRecipe[]}, TContext> => {

const mutationKey = ['insertAllCraftingRecipes'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllCraftingRecipes>>, {universe: string;data: CraftingRecipe[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllCraftingRecipes(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllCraftingRecipesMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllCraftingRecipes>>>
    export type InsertAllCraftingRecipesMutationBody = CraftingRecipe[]
    export type InsertAllCraftingRecipesMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllCraftingRecipes = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllCraftingRecipes>>, TError,{universe: string;data: CraftingRecipe[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllCraftingRecipes>>,
        TError,
        {universe: string;data: CraftingRecipe[]},
        TContext
      > => {

      const mutationOptions = getInsertAllCraftingRecipesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes an object from the database
 */
export const deleteCraftingRecipe = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/crafting-recipes/${id}`,options
    );
  }



export const getDeleteCraftingRecipeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCraftingRecipe>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCraftingRecipe>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deleteCraftingRecipe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCraftingRecipe>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deleteCraftingRecipe(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCraftingRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCraftingRecipe>>>
    
    export type DeleteCraftingRecipeMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeleteCraftingRecipe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCraftingRecipe>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCraftingRecipe>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteCraftingRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getCraftingRecipe = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CraftingRecipe>> => {
    
    
    return axios.get(
      `/api/${universe}/crafting-recipes/${id}`,options
    );
  }




export const getGetCraftingRecipeQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/api/${universe}/crafting-recipes/${id}`
    ] as const;
    }

    
export const getGetCraftingRecipeQueryOptions = <TData = Awaited<ReturnType<typeof getCraftingRecipe>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCraftingRecipeQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCraftingRecipe>>> = ({ signal }) => getCraftingRecipe(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCraftingRecipeQueryResult = NonNullable<Awaited<ReturnType<typeof getCraftingRecipe>>>
export type GetCraftingRecipeQueryError = AxiosError<unknown>


export function useGetCraftingRecipe<TData = Awaited<ReturnType<typeof getCraftingRecipe>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCraftingRecipe>>,
          TError,
          Awaited<ReturnType<typeof getCraftingRecipe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCraftingRecipe<TData = Awaited<ReturnType<typeof getCraftingRecipe>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCraftingRecipe>>,
          TError,
          Awaited<ReturnType<typeof getCraftingRecipe>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCraftingRecipe<TData = Awaited<ReturnType<typeof getCraftingRecipe>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetCraftingRecipe<TData = Awaited<ReturnType<typeof getCraftingRecipe>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCraftingRecipe>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCraftingRecipeQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updateCraftingRecipe = (
    universe: string,
    id: string,
    craftingRecipe: CraftingRecipe, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CraftingRecipe>> => {
    
    
    return axios.put(
      `/api/${universe}/crafting-recipes/${id}`,
      craftingRecipe,options
    );
  }



export const getUpdateCraftingRecipeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCraftingRecipe>>, TError,{universe: string;id: string;data: CraftingRecipe}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCraftingRecipe>>, TError,{universe: string;id: string;data: CraftingRecipe}, TContext> => {

const mutationKey = ['updateCraftingRecipe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCraftingRecipe>>, {universe: string;id: string;data: CraftingRecipe}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updateCraftingRecipe(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCraftingRecipeMutationResult = NonNullable<Awaited<ReturnType<typeof updateCraftingRecipe>>>
    export type UpdateCraftingRecipeMutationBody = CraftingRecipe
    export type UpdateCraftingRecipeMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdateCraftingRecipe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCraftingRecipe>>, TError,{universe: string;id: string;data: CraftingRecipe}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCraftingRecipe>>,
        TError,
        {universe: string;id: string;data: CraftingRecipe},
        TContext
      > => {

      const mutationOptions = getUpdateCraftingRecipeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    