/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteAllCharactersParams,
  PnPCharacterDTO,
  RecalculateEntries
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllCharacters = (
    universe: string,
    params: DeleteAllCharactersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/characters`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllCharactersMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllCharacters>>, TError,{universe: string;params: DeleteAllCharactersParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllCharacters>>, TError,{universe: string;params: DeleteAllCharactersParams}, TContext> => {

const mutationKey = ['deleteAllCharacters'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllCharacters>>, {universe: string;params: DeleteAllCharactersParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllCharacters(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllCharactersMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllCharacters>>>
    
    export type DeleteAllCharactersMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllCharacters = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllCharacters>>, TError,{universe: string;params: DeleteAllCharactersParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllCharacters>>,
        TError,
        {universe: string;params: DeleteAllCharactersParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllCharactersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all characters from the database
 */
export const getAllCharacters = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PnPCharacterDTO[]>> => {
    
    
    return axios.get(
      `/api/${universe}/characters`,options
    );
  }




export const getGetAllCharactersQueryKey = (universe?: string,) => {
    return [
    `/api/${universe}/characters`
    ] as const;
    }

    
export const getGetAllCharactersQueryOptions = <TData = Awaited<ReturnType<typeof getAllCharacters>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCharactersQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCharacters>>> = ({ signal }) => getAllCharacters(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCharactersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCharacters>>>
export type GetAllCharactersQueryError = AxiosError<unknown>


export function useGetAllCharacters<TData = Awaited<ReturnType<typeof getAllCharacters>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCharacters>>,
          TError,
          Awaited<ReturnType<typeof getAllCharacters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCharacters<TData = Awaited<ReturnType<typeof getAllCharacters>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCharacters>>,
          TError,
          Awaited<ReturnType<typeof getAllCharacters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCharacters<TData = Awaited<ReturnType<typeof getAllCharacters>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all characters from the database
 */

export function useGetAllCharacters<TData = Awaited<ReturnType<typeof getAllCharacters>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCharactersQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllCharacters = (
    universe: string,
    pnPCharacterDTO: PnPCharacterDTO[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PnPCharacterDTO[]>> => {
    
    
    return axios.post(
      `/api/${universe}/characters`,
      pnPCharacterDTO,options
    );
  }



export const getInsertAllCharactersMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllCharacters>>, TError,{universe: string;data: PnPCharacterDTO[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllCharacters>>, TError,{universe: string;data: PnPCharacterDTO[]}, TContext> => {

const mutationKey = ['insertAllCharacters'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllCharacters>>, {universe: string;data: PnPCharacterDTO[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllCharacters(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllCharactersMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllCharacters>>>
    export type InsertAllCharactersMutationBody = PnPCharacterDTO[]
    export type InsertAllCharactersMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllCharacters = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllCharacters>>, TError,{universe: string;data: PnPCharacterDTO[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllCharacters>>,
        TError,
        {universe: string;data: PnPCharacterDTO[]},
        TContext
      > => {

      const mutationOptions = getInsertAllCharactersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Recalculates all entries of the character
 */
export const recalculateEntries = (
    universe: string,
    pnPCharacterDTO: PnPCharacterDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RecalculateEntries>> => {
    
    
    return axios.post(
      `/api/${universe}/characters/recalculate`,
      pnPCharacterDTO,options
    );
  }



export const getRecalculateEntriesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recalculateEntries>>, TError,{universe: string;data: PnPCharacterDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof recalculateEntries>>, TError,{universe: string;data: PnPCharacterDTO}, TContext> => {

const mutationKey = ['recalculateEntries'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recalculateEntries>>, {universe: string;data: PnPCharacterDTO}> = (props) => {
          const {universe,data} = props ?? {};

          return  recalculateEntries(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecalculateEntriesMutationResult = NonNullable<Awaited<ReturnType<typeof recalculateEntries>>>
    export type RecalculateEntriesMutationBody = PnPCharacterDTO
    export type RecalculateEntriesMutationError = AxiosError<unknown>

    /**
 * @summary Recalculates all entries of the character
 */
export const useRecalculateEntries = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recalculateEntries>>, TError,{universe: string;data: PnPCharacterDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recalculateEntries>>,
        TError,
        {universe: string;data: PnPCharacterDTO},
        TContext
      > => {

      const mutationOptions = getRecalculateEntriesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes an object from the database
 */
export const deleteCharacter = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/characters/${id}`,options
    );
  }



export const getDeleteCharacterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deleteCharacter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCharacter>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deleteCharacter(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCharacter>>>
    
    export type DeleteCharacterMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeleteCharacter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCharacter>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteCharacterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getCharacter = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PnPCharacterDTO>> => {
    
    
    return axios.get(
      `/api/${universe}/characters/${id}`,options
    );
  }




export const getGetCharacterQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/api/${universe}/characters/${id}`
    ] as const;
    }

    
export const getGetCharacterQueryOptions = <TData = Awaited<ReturnType<typeof getCharacter>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCharacterQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCharacter>>> = ({ signal }) => getCharacter(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCharacterQueryResult = NonNullable<Awaited<ReturnType<typeof getCharacter>>>
export type GetCharacterQueryError = AxiosError<unknown>


export function useGetCharacter<TData = Awaited<ReturnType<typeof getCharacter>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharacter>>,
          TError,
          Awaited<ReturnType<typeof getCharacter>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharacter<TData = Awaited<ReturnType<typeof getCharacter>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCharacter>>,
          TError,
          Awaited<ReturnType<typeof getCharacter>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCharacter<TData = Awaited<ReturnType<typeof getCharacter>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetCharacter<TData = Awaited<ReturnType<typeof getCharacter>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCharacter>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCharacterQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updateCharacter = (
    universe: string,
    id: string,
    pnPCharacterDTO: PnPCharacterDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PnPCharacterDTO>> => {
    
    
    return axios.put(
      `/api/${universe}/characters/${id}`,
      pnPCharacterDTO,options
    );
  }



export const getUpdateCharacterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{universe: string;id: string;data: PnPCharacterDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{universe: string;id: string;data: PnPCharacterDTO}, TContext> => {

const mutationKey = ['updateCharacter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCharacter>>, {universe: string;id: string;data: PnPCharacterDTO}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updateCharacter(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof updateCharacter>>>
    export type UpdateCharacterMutationBody = PnPCharacterDTO
    export type UpdateCharacterMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdateCharacter = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{universe: string;id: string;data: PnPCharacterDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCharacter>>,
        TError,
        {universe: string;id: string;data: PnPCharacterDTO},
        TContext
      > => {

      const mutationOptions = getUpdateCharacterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    