/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteAllNationsParams,
  GetAllNationsParams,
  Nation
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllNations = (
    universe: string,
    params: DeleteAllNationsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/nations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllNationsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllNations>>, TError,{universe: string;params: DeleteAllNationsParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllNations>>, TError,{universe: string;params: DeleteAllNationsParams}, TContext> => {

const mutationKey = ['deleteAllNations'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllNations>>, {universe: string;params: DeleteAllNationsParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllNations(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllNationsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllNations>>>
    
    export type DeleteAllNationsMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllNations = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllNations>>, TError,{universe: string;params: DeleteAllNationsParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllNations>>,
        TError,
        {universe: string;params: DeleteAllNationsParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllNationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all objects from the database
 */
export const getAllNations = (
    universe: string,
    params?: GetAllNationsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Nation[]>> => {
    
    
    return axios.get(
      `/api/${universe}/nations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllNationsQueryKey = (universe?: string,
    params?: GetAllNationsParams,) => {
    return [
    `/api/${universe}/nations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllNationsQueryOptions = <TData = Awaited<ReturnType<typeof getAllNations>>, TError = AxiosError<unknown>>(universe: string,
    params?: GetAllNationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllNationsQueryKey(universe,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllNations>>> = ({ signal }) => getAllNations(universe,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllNationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllNations>>>
export type GetAllNationsQueryError = AxiosError<unknown>


export function useGetAllNations<TData = Awaited<ReturnType<typeof getAllNations>>, TError = AxiosError<unknown>>(
 universe: string,
    params: undefined |  GetAllNationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllNations>>,
          TError,
          Awaited<ReturnType<typeof getAllNations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllNations<TData = Awaited<ReturnType<typeof getAllNations>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllNationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllNations>>,
          TError,
          Awaited<ReturnType<typeof getAllNations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllNations<TData = Awaited<ReturnType<typeof getAllNations>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllNationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all objects from the database
 */

export function useGetAllNations<TData = Awaited<ReturnType<typeof getAllNations>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllNationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllNations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllNationsQueryOptions(universe,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllNations = (
    universe: string,
    nation: Nation[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Nation[]>> => {
    
    
    return axios.post(
      `/api/${universe}/nations`,
      nation,options
    );
  }



export const getInsertAllNationsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllNations>>, TError,{universe: string;data: Nation[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllNations>>, TError,{universe: string;data: Nation[]}, TContext> => {

const mutationKey = ['insertAllNations'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllNations>>, {universe: string;data: Nation[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllNations(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllNationsMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllNations>>>
    export type InsertAllNationsMutationBody = Nation[]
    export type InsertAllNationsMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllNations = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllNations>>, TError,{universe: string;data: Nation[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllNations>>,
        TError,
        {universe: string;data: Nation[]},
        TContext
      > => {

      const mutationOptions = getInsertAllNationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes an object from the database
 */
export const deleteNation = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/nations/${id}`,options
    );
  }



export const getDeleteNationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNation>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNation>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deleteNation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNation>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deleteNation(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNation>>>
    
    export type DeleteNationMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeleteNation = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNation>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNation>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteNationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getNation = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Nation>> => {
    
    
    return axios.get(
      `/api/${universe}/nations/${id}`,options
    );
  }




export const getGetNationQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/api/${universe}/nations/${id}`
    ] as const;
    }

    
export const getGetNationQueryOptions = <TData = Awaited<ReturnType<typeof getNation>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNationQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNation>>> = ({ signal }) => getNation(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNationQueryResult = NonNullable<Awaited<ReturnType<typeof getNation>>>
export type GetNationQueryError = AxiosError<unknown>


export function useGetNation<TData = Awaited<ReturnType<typeof getNation>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNation>>,
          TError,
          Awaited<ReturnType<typeof getNation>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNation<TData = Awaited<ReturnType<typeof getNation>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNation>>,
          TError,
          Awaited<ReturnType<typeof getNation>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNation<TData = Awaited<ReturnType<typeof getNation>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetNation<TData = Awaited<ReturnType<typeof getNation>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNation>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNationQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updateNation = (
    universe: string,
    id: string,
    nation: Nation, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Nation>> => {
    
    
    return axios.put(
      `/api/${universe}/nations/${id}`,
      nation,options
    );
  }



export const getUpdateNationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNation>>, TError,{universe: string;id: string;data: Nation}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateNation>>, TError,{universe: string;id: string;data: Nation}, TContext> => {

const mutationKey = ['updateNation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNation>>, {universe: string;id: string;data: Nation}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updateNation(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNationMutationResult = NonNullable<Awaited<ReturnType<typeof updateNation>>>
    export type UpdateNationMutationBody = Nation
    export type UpdateNationMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdateNation = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNation>>, TError,{universe: string;id: string;data: Nation}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNation>>,
        TError,
        {universe: string;id: string;data: Nation},
        TContext
      > => {

      const mutationOptions = getUpdateNationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    