/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddUpgradeToItem200,
  RemoveUpgradeFromItem200,
  UpgradeRemovalRequestItemStack,
  UpgradeRequestItemStack
} from '.././model';





/**
 * @summary Upgrades the given equipment
 */
export const addUpgradeToItem = (
    upgradeRequestItemStack: UpgradeRequestItemStack, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddUpgradeToItem200>> => {
    
    
    return axios.post(
      `/api/upgrade-item/add`,
      upgradeRequestItemStack,options
    );
  }



export const getAddUpgradeToItemMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUpgradeToItem>>, TError,{data: UpgradeRequestItemStack}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addUpgradeToItem>>, TError,{data: UpgradeRequestItemStack}, TContext> => {

const mutationKey = ['addUpgradeToItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addUpgradeToItem>>, {data: UpgradeRequestItemStack}> = (props) => {
          const {data} = props ?? {};

          return  addUpgradeToItem(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddUpgradeToItemMutationResult = NonNullable<Awaited<ReturnType<typeof addUpgradeToItem>>>
    export type AddUpgradeToItemMutationBody = UpgradeRequestItemStack
    export type AddUpgradeToItemMutationError = AxiosError<unknown>

    /**
 * @summary Upgrades the given equipment
 */
export const useAddUpgradeToItem = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUpgradeToItem>>, TError,{data: UpgradeRequestItemStack}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addUpgradeToItem>>,
        TError,
        {data: UpgradeRequestItemStack},
        TContext
      > => {

      const mutationOptions = getAddUpgradeToItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove an upgrades from the given equipment
 */
export const removeUpgradeFromItem = (
    upgradeRemovalRequestItemStack: UpgradeRemovalRequestItemStack, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RemoveUpgradeFromItem200>> => {
    
    
    return axios.post(
      `/api/upgrade-item/remove`,
      upgradeRemovalRequestItemStack,options
    );
  }



export const getRemoveUpgradeFromItemMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUpgradeFromItem>>, TError,{data: UpgradeRemovalRequestItemStack}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeUpgradeFromItem>>, TError,{data: UpgradeRemovalRequestItemStack}, TContext> => {

const mutationKey = ['removeUpgradeFromItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeUpgradeFromItem>>, {data: UpgradeRemovalRequestItemStack}> = (props) => {
          const {data} = props ?? {};

          return  removeUpgradeFromItem(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveUpgradeFromItemMutationResult = NonNullable<Awaited<ReturnType<typeof removeUpgradeFromItem>>>
    export type RemoveUpgradeFromItemMutationBody = UpgradeRemovalRequestItemStack
    export type RemoveUpgradeFromItemMutationError = AxiosError<unknown>

    /**
 * @summary Remove an upgrades from the given equipment
 */
export const useRemoveUpgradeFromItem = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUpgradeFromItem>>, TError,{data: UpgradeRemovalRequestItemStack}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeUpgradeFromItem>>,
        TError,
        {data: UpgradeRemovalRequestItemStack},
        TContext
      > => {

      const mutationOptions = getRemoveUpgradeFromItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    