/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteAllSpellsParams,
  GetAllSpellsParams,
  Spell
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllSpells = (
    universe: string,
    params: DeleteAllSpellsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/spells`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllSpellsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllSpells>>, TError,{universe: string;params: DeleteAllSpellsParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllSpells>>, TError,{universe: string;params: DeleteAllSpellsParams}, TContext> => {

const mutationKey = ['deleteAllSpells'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllSpells>>, {universe: string;params: DeleteAllSpellsParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllSpells(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllSpellsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllSpells>>>
    
    export type DeleteAllSpellsMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllSpells = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllSpells>>, TError,{universe: string;params: DeleteAllSpellsParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllSpells>>,
        TError,
        {universe: string;params: DeleteAllSpellsParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllSpellsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all objects from the database
 */
export const getAllSpells = (
    universe: string,
    params?: GetAllSpellsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Spell[]>> => {
    
    
    return axios.get(
      `/api/${universe}/spells`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllSpellsQueryKey = (universe?: string,
    params?: GetAllSpellsParams,) => {
    return [
    `/api/${universe}/spells`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllSpellsQueryOptions = <TData = Awaited<ReturnType<typeof getAllSpells>>, TError = AxiosError<unknown>>(universe: string,
    params?: GetAllSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSpellsQueryKey(universe,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSpells>>> = ({ signal }) => getAllSpells(universe,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllSpellsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSpells>>>
export type GetAllSpellsQueryError = AxiosError<unknown>


export function useGetAllSpells<TData = Awaited<ReturnType<typeof getAllSpells>>, TError = AxiosError<unknown>>(
 universe: string,
    params: undefined |  GetAllSpellsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSpells>>,
          TError,
          Awaited<ReturnType<typeof getAllSpells>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSpells<TData = Awaited<ReturnType<typeof getAllSpells>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSpells>>,
          TError,
          Awaited<ReturnType<typeof getAllSpells>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSpells<TData = Awaited<ReturnType<typeof getAllSpells>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all objects from the database
 */

export function useGetAllSpells<TData = Awaited<ReturnType<typeof getAllSpells>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllSpellsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSpells>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllSpellsQueryOptions(universe,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllSpells = (
    universe: string,
    spell: Spell[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Spell[]>> => {
    
    
    return axios.post(
      `/api/${universe}/spells`,
      spell,options
    );
  }



export const getInsertAllSpellsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllSpells>>, TError,{universe: string;data: Spell[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllSpells>>, TError,{universe: string;data: Spell[]}, TContext> => {

const mutationKey = ['insertAllSpells'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllSpells>>, {universe: string;data: Spell[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllSpells(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllSpellsMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllSpells>>>
    export type InsertAllSpellsMutationBody = Spell[]
    export type InsertAllSpellsMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllSpells = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllSpells>>, TError,{universe: string;data: Spell[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllSpells>>,
        TError,
        {universe: string;data: Spell[]},
        TContext
      > => {

      const mutationOptions = getInsertAllSpellsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes an object from the database
 */
export const deleteSpell = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/spells/${id}`,options
    );
  }



export const getDeleteSpellMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSpell>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSpell>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deleteSpell'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSpell>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deleteSpell(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSpellMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSpell>>>
    
    export type DeleteSpellMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeleteSpell = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSpell>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSpell>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteSpellMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getSpell = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Spell>> => {
    
    
    return axios.get(
      `/api/${universe}/spells/${id}`,options
    );
  }




export const getGetSpellQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/api/${universe}/spells/${id}`
    ] as const;
    }

    
export const getGetSpellQueryOptions = <TData = Awaited<ReturnType<typeof getSpell>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSpellQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSpell>>> = ({ signal }) => getSpell(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSpellQueryResult = NonNullable<Awaited<ReturnType<typeof getSpell>>>
export type GetSpellQueryError = AxiosError<unknown>


export function useGetSpell<TData = Awaited<ReturnType<typeof getSpell>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpell>>,
          TError,
          Awaited<ReturnType<typeof getSpell>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpell<TData = Awaited<ReturnType<typeof getSpell>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpell>>,
          TError,
          Awaited<ReturnType<typeof getSpell>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpell<TData = Awaited<ReturnType<typeof getSpell>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetSpell<TData = Awaited<ReturnType<typeof getSpell>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpell>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSpellQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updateSpell = (
    universe: string,
    id: string,
    spell: Spell, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Spell>> => {
    
    
    return axios.put(
      `/api/${universe}/spells/${id}`,
      spell,options
    );
  }



export const getUpdateSpellMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSpell>>, TError,{universe: string;id: string;data: Spell}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateSpell>>, TError,{universe: string;id: string;data: Spell}, TContext> => {

const mutationKey = ['updateSpell'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSpell>>, {universe: string;id: string;data: Spell}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updateSpell(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSpellMutationResult = NonNullable<Awaited<ReturnType<typeof updateSpell>>>
    export type UpdateSpellMutationBody = Spell
    export type UpdateSpellMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdateSpell = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSpell>>, TError,{universe: string;id: string;data: Spell}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSpell>>,
        TError,
        {universe: string;id: string;data: Spell},
        TContext
      > => {

      const mutationOptions = getUpdateSpellMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    