/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteAllPrimaryAttributesParams,
  GetAllPrimaryAttributesParams,
  PrimaryAttribute
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllPrimaryAttributes = (
    universe: string,
    params: DeleteAllPrimaryAttributesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/${universe}/primary-attributes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllPrimaryAttributesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>, TError,{universe: string;params: DeleteAllPrimaryAttributesParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>, TError,{universe: string;params: DeleteAllPrimaryAttributesParams}, TContext> => {

const mutationKey = ['deleteAllPrimaryAttributes'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>, {universe: string;params: DeleteAllPrimaryAttributesParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllPrimaryAttributes(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllPrimaryAttributesMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>>
    
    export type DeleteAllPrimaryAttributesMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllPrimaryAttributes = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>, TError,{universe: string;params: DeleteAllPrimaryAttributesParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllPrimaryAttributes>>,
        TError,
        {universe: string;params: DeleteAllPrimaryAttributesParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllPrimaryAttributesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all objects from the database
 */
export const getAllPrimaryAttributes = (
    universe: string,
    params?: GetAllPrimaryAttributesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PrimaryAttribute[]>> => {
    
    
    return axios.get(
      `/${universe}/primary-attributes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllPrimaryAttributesQueryKey = (universe?: string,
    params?: GetAllPrimaryAttributesParams,) => {
    return [
    `/${universe}/primary-attributes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllPrimaryAttributesQueryOptions = <TData = Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError = AxiosError<unknown>>(universe: string,
    params?: GetAllPrimaryAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPrimaryAttributesQueryKey(universe,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPrimaryAttributes>>> = ({ signal }) => getAllPrimaryAttributes(universe,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllPrimaryAttributesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPrimaryAttributes>>>
export type GetAllPrimaryAttributesQueryError = AxiosError<unknown>


export function useGetAllPrimaryAttributes<TData = Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError = AxiosError<unknown>>(
 universe: string,
    params: undefined |  GetAllPrimaryAttributesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPrimaryAttributes>>,
          TError,
          Awaited<ReturnType<typeof getAllPrimaryAttributes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPrimaryAttributes<TData = Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllPrimaryAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPrimaryAttributes>>,
          TError,
          Awaited<ReturnType<typeof getAllPrimaryAttributes>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllPrimaryAttributes<TData = Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllPrimaryAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all objects from the database
 */

export function useGetAllPrimaryAttributes<TData = Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllPrimaryAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPrimaryAttributes>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllPrimaryAttributesQueryOptions(universe,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllPrimaryAttributes = (
    universe: string,
    primaryAttribute: PrimaryAttribute[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PrimaryAttribute[]>> => {
    
    
    return axios.post(
      `/${universe}/primary-attributes`,
      primaryAttribute,options
    );
  }



export const getInsertAllPrimaryAttributesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext> => {

const mutationKey = ['insertAllPrimaryAttributes'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllPrimaryAttributes>>, {universe: string;data: PrimaryAttribute[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllPrimaryAttributes(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllPrimaryAttributesMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllPrimaryAttributes>>>
    export type InsertAllPrimaryAttributesMutationBody = PrimaryAttribute[]
    export type InsertAllPrimaryAttributesMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllPrimaryAttributes = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllPrimaryAttributes>>,
        TError,
        {universe: string;data: PrimaryAttribute[]},
        TContext
      > => {

      const mutationOptions = getInsertAllPrimaryAttributesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Sets all primary attributes of the universe
 */
export const setAllPrimaryAttributes = (
    universe: string,
    primaryAttribute: PrimaryAttribute[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/${universe}/primary-attributes`,
      primaryAttribute,options
    );
  }



export const getSetAllPrimaryAttributesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof setAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext> => {

const mutationKey = ['setAllPrimaryAttributes'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setAllPrimaryAttributes>>, {universe: string;data: PrimaryAttribute[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  setAllPrimaryAttributes(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetAllPrimaryAttributesMutationResult = NonNullable<Awaited<ReturnType<typeof setAllPrimaryAttributes>>>
    export type SetAllPrimaryAttributesMutationBody = PrimaryAttribute[]
    export type SetAllPrimaryAttributesMutationError = AxiosError<unknown>

    /**
 * @summary Sets all primary attributes of the universe
 */
export const useSetAllPrimaryAttributes = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setAllPrimaryAttributes>>, TError,{universe: string;data: PrimaryAttribute[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setAllPrimaryAttributes>>,
        TError,
        {universe: string;data: PrimaryAttribute[]},
        TContext
      > => {

      const mutationOptions = getSetAllPrimaryAttributesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes an object from the database
 */
export const deletePrimaryAttribute = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/${universe}/primary-attributes/${id}`,options
    );
  }



export const getDeletePrimaryAttributeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrimaryAttribute>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deletePrimaryAttribute>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deletePrimaryAttribute'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePrimaryAttribute>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deletePrimaryAttribute(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePrimaryAttributeMutationResult = NonNullable<Awaited<ReturnType<typeof deletePrimaryAttribute>>>
    
    export type DeletePrimaryAttributeMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeletePrimaryAttribute = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrimaryAttribute>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePrimaryAttribute>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeletePrimaryAttributeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getPrimaryAttribute = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PrimaryAttribute>> => {
    
    
    return axios.get(
      `/${universe}/primary-attributes/${id}`,options
    );
  }




export const getGetPrimaryAttributeQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/${universe}/primary-attributes/${id}`
    ] as const;
    }

    
export const getGetPrimaryAttributeQueryOptions = <TData = Awaited<ReturnType<typeof getPrimaryAttribute>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrimaryAttributeQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrimaryAttribute>>> = ({ signal }) => getPrimaryAttribute(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrimaryAttributeQueryResult = NonNullable<Awaited<ReturnType<typeof getPrimaryAttribute>>>
export type GetPrimaryAttributeQueryError = AxiosError<unknown>


export function useGetPrimaryAttribute<TData = Awaited<ReturnType<typeof getPrimaryAttribute>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrimaryAttribute>>,
          TError,
          Awaited<ReturnType<typeof getPrimaryAttribute>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrimaryAttribute<TData = Awaited<ReturnType<typeof getPrimaryAttribute>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrimaryAttribute>>,
          TError,
          Awaited<ReturnType<typeof getPrimaryAttribute>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrimaryAttribute<TData = Awaited<ReturnType<typeof getPrimaryAttribute>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetPrimaryAttribute<TData = Awaited<ReturnType<typeof getPrimaryAttribute>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrimaryAttribute>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrimaryAttributeQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updatePrimaryAttribute = (
    universe: string,
    id: string,
    primaryAttribute: PrimaryAttribute, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PrimaryAttribute>> => {
    
    
    return axios.put(
      `/${universe}/primary-attributes/${id}`,
      primaryAttribute,options
    );
  }



export const getUpdatePrimaryAttributeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePrimaryAttribute>>, TError,{universe: string;id: string;data: PrimaryAttribute}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePrimaryAttribute>>, TError,{universe: string;id: string;data: PrimaryAttribute}, TContext> => {

const mutationKey = ['updatePrimaryAttribute'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePrimaryAttribute>>, {universe: string;id: string;data: PrimaryAttribute}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updatePrimaryAttribute(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePrimaryAttributeMutationResult = NonNullable<Awaited<ReturnType<typeof updatePrimaryAttribute>>>
    export type UpdatePrimaryAttributeMutationBody = PrimaryAttribute
    export type UpdatePrimaryAttributeMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdatePrimaryAttribute = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePrimaryAttribute>>, TError,{universe: string;id: string;data: PrimaryAttribute}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePrimaryAttribute>>,
        TError,
        {universe: string;id: string;data: PrimaryAttribute},
        TContext
      > => {

      const mutationOptions = getUpdatePrimaryAttributeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    