/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Armor,
  DeleteAllItemsParams,
  GetAllItemsParams,
  Item,
  Jewellery,
  Shield,
  Weapon
} from '.././model';





/**
 * @summary Deletes all objects with the given ids from the database
 */
export const deleteAllItems = (
    universe: string,
    params: DeleteAllItemsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteAllItemsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllItems>>, TError,{universe: string;params: DeleteAllItemsParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllItems>>, TError,{universe: string;params: DeleteAllItemsParams}, TContext> => {

const mutationKey = ['deleteAllItems'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllItems>>, {universe: string;params: DeleteAllItemsParams}> = (props) => {
          const {universe,params} = props ?? {};

          return  deleteAllItems(universe,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllItemsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllItems>>>
    
    export type DeleteAllItemsMutationError = AxiosError<unknown>

    /**
 * @summary Deletes all objects with the given ids from the database
 */
export const useDeleteAllItems = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllItems>>, TError,{universe: string;params: DeleteAllItemsParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAllItems>>,
        TError,
        {universe: string;params: DeleteAllItemsParams},
        TContext
      > => {

      const mutationOptions = getDeleteAllItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all objects from the database
 */
export const getAllItems = (
    universe: string,
    params?: GetAllItemsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Item[]>> => {
    
    
    return axios.get(
      `/api/${universe}/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllItemsQueryKey = (universe?: string,
    params?: GetAllItemsParams,) => {
    return [
    `/api/${universe}/items`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllItemsQueryOptions = <TData = Awaited<ReturnType<typeof getAllItems>>, TError = AxiosError<unknown>>(universe: string,
    params?: GetAllItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllItemsQueryKey(universe,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllItems>>> = ({ signal }) => getAllItems(universe,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllItems>>>
export type GetAllItemsQueryError = AxiosError<unknown>


export function useGetAllItems<TData = Awaited<ReturnType<typeof getAllItems>>, TError = AxiosError<unknown>>(
 universe: string,
    params: undefined |  GetAllItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllItems>>,
          TError,
          Awaited<ReturnType<typeof getAllItems>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllItems<TData = Awaited<ReturnType<typeof getAllItems>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllItems>>,
          TError,
          Awaited<ReturnType<typeof getAllItems>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllItems<TData = Awaited<ReturnType<typeof getAllItems>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all objects from the database
 */

export function useGetAllItems<TData = Awaited<ReturnType<typeof getAllItems>>, TError = AxiosError<unknown>>(
 universe: string,
    params?: GetAllItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllItems>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllItemsQueryOptions(universe,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Inserts the objects into the database
 */
export const insertAllItems = (
    universe: string,
    item: Item[], options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Item[]>> => {
    
    
    return axios.post(
      `/api/${universe}/items`,
      item,options
    );
  }



export const getInsertAllItemsMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllItems>>, TError,{universe: string;data: Item[]}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof insertAllItems>>, TError,{universe: string;data: Item[]}, TContext> => {

const mutationKey = ['insertAllItems'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof insertAllItems>>, {universe: string;data: Item[]}> = (props) => {
          const {universe,data} = props ?? {};

          return  insertAllItems(universe,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InsertAllItemsMutationResult = NonNullable<Awaited<ReturnType<typeof insertAllItems>>>
    export type InsertAllItemsMutationBody = Item[]
    export type InsertAllItemsMutationError = AxiosError<unknown>

    /**
 * @summary Inserts the objects into the database
 */
export const useInsertAllItems = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof insertAllItems>>, TError,{universe: string;data: Item[]}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof insertAllItems>>,
        TError,
        {universe: string;data: Item[]},
        TContext
      > => {

      const mutationOptions = getInsertAllItemsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get all weapons from the database
 */
export const getAllArmor = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Armor[]>> => {
    
    
    return axios.get(
      `/api/${universe}/items/armor`,options
    );
  }




export const getGetAllArmorQueryKey = (universe?: string,) => {
    return [
    `/api/${universe}/items/armor`
    ] as const;
    }

    
export const getGetAllArmorQueryOptions = <TData = Awaited<ReturnType<typeof getAllArmor>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllArmorQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllArmor>>> = ({ signal }) => getAllArmor(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllArmorQueryResult = NonNullable<Awaited<ReturnType<typeof getAllArmor>>>
export type GetAllArmorQueryError = AxiosError<unknown>


export function useGetAllArmor<TData = Awaited<ReturnType<typeof getAllArmor>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllArmor>>,
          TError,
          Awaited<ReturnType<typeof getAllArmor>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllArmor<TData = Awaited<ReturnType<typeof getAllArmor>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllArmor>>,
          TError,
          Awaited<ReturnType<typeof getAllArmor>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllArmor<TData = Awaited<ReturnType<typeof getAllArmor>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all weapons from the database
 */

export function useGetAllArmor<TData = Awaited<ReturnType<typeof getAllArmor>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArmor>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllArmorQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all weapons from the database
 */
export const getAllJewellery = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Jewellery[]>> => {
    
    
    return axios.get(
      `/api/${universe}/items/jewellery`,options
    );
  }




export const getGetAllJewelleryQueryKey = (universe?: string,) => {
    return [
    `/api/${universe}/items/jewellery`
    ] as const;
    }

    
export const getGetAllJewelleryQueryOptions = <TData = Awaited<ReturnType<typeof getAllJewellery>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllJewelleryQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllJewellery>>> = ({ signal }) => getAllJewellery(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllJewelleryQueryResult = NonNullable<Awaited<ReturnType<typeof getAllJewellery>>>
export type GetAllJewelleryQueryError = AxiosError<unknown>


export function useGetAllJewellery<TData = Awaited<ReturnType<typeof getAllJewellery>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllJewellery>>,
          TError,
          Awaited<ReturnType<typeof getAllJewellery>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllJewellery<TData = Awaited<ReturnType<typeof getAllJewellery>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllJewellery>>,
          TError,
          Awaited<ReturnType<typeof getAllJewellery>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllJewellery<TData = Awaited<ReturnType<typeof getAllJewellery>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all weapons from the database
 */

export function useGetAllJewellery<TData = Awaited<ReturnType<typeof getAllJewellery>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJewellery>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllJewelleryQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all weapons from the database
 */
export const getAllShields = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Shield[]>> => {
    
    
    return axios.get(
      `/api/${universe}/items/shields`,options
    );
  }




export const getGetAllShieldsQueryKey = (universe?: string,) => {
    return [
    `/api/${universe}/items/shields`
    ] as const;
    }

    
export const getGetAllShieldsQueryOptions = <TData = Awaited<ReturnType<typeof getAllShields>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllShieldsQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllShields>>> = ({ signal }) => getAllShields(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllShieldsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllShields>>>
export type GetAllShieldsQueryError = AxiosError<unknown>


export function useGetAllShields<TData = Awaited<ReturnType<typeof getAllShields>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShields>>,
          TError,
          Awaited<ReturnType<typeof getAllShields>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllShields<TData = Awaited<ReturnType<typeof getAllShields>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShields>>,
          TError,
          Awaited<ReturnType<typeof getAllShields>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllShields<TData = Awaited<ReturnType<typeof getAllShields>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all weapons from the database
 */

export function useGetAllShields<TData = Awaited<ReturnType<typeof getAllShields>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllShields>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllShieldsQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all weapons from the database
 */
export const getAllWeapons = (
    universe: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Weapon[]>> => {
    
    
    return axios.get(
      `/api/${universe}/items/weapons`,options
    );
  }




export const getGetAllWeaponsQueryKey = (universe?: string,) => {
    return [
    `/api/${universe}/items/weapons`
    ] as const;
    }

    
export const getGetAllWeaponsQueryOptions = <TData = Awaited<ReturnType<typeof getAllWeapons>>, TError = AxiosError<unknown>>(universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllWeaponsQueryKey(universe);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllWeapons>>> = ({ signal }) => getAllWeapons(universe, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllWeaponsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWeapons>>>
export type GetAllWeaponsQueryError = AxiosError<unknown>


export function useGetAllWeapons<TData = Awaited<ReturnType<typeof getAllWeapons>>, TError = AxiosError<unknown>>(
 universe: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWeapons>>,
          TError,
          Awaited<ReturnType<typeof getAllWeapons>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWeapons<TData = Awaited<ReturnType<typeof getAllWeapons>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWeapons>>,
          TError,
          Awaited<ReturnType<typeof getAllWeapons>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWeapons<TData = Awaited<ReturnType<typeof getAllWeapons>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all weapons from the database
 */

export function useGetAllWeapons<TData = Awaited<ReturnType<typeof getAllWeapons>>, TError = AxiosError<unknown>>(
 universe: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWeapons>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllWeaponsQueryOptions(universe,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Deletes an object from the database
 */
export const deleteItem = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/${universe}/items/${id}`,options
    );
  }



export const getDeleteItemMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{universe: string;id: string}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {universe: string;id: string}> = (props) => {
          const {universe,id} = props ?? {};

          return  deleteItem(universe,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>
    
    export type DeleteItemMutationError = AxiosError<unknown>

    /**
 * @summary Deletes an object from the database
 */
export const useDeleteItem = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{universe: string;id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {universe: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get an object from the database
 */
export const getItem = (
    universe: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Item>> => {
    
    
    return axios.get(
      `/api/${universe}/items/${id}`,options
    );
  }




export const getGetItemQueryKey = (universe?: string,
    id?: string,) => {
    return [
    `/api/${universe}/items/${id}`
    ] as const;
    }

    
export const getGetItemQueryOptions = <TData = Awaited<ReturnType<typeof getItem>>, TError = AxiosError<unknown>>(universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemQueryKey(universe,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem>>> = ({ signal }) => getItem(universe,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universe && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemQueryResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type GetItemQueryError = AxiosError<unknown>


export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an object from the database
 */

export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = AxiosError<unknown>>(
 universe: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemQueryOptions(universe,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Updates an object in the database
 */
export const updateItem = (
    universe: string,
    id: string,
    item: Item, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Item>> => {
    
    
    return axios.put(
      `/api/${universe}/items/${id}`,
      item,options
    );
  }



export const getUpdateItemMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{universe: string;id: string;data: Item}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{universe: string;id: string;data: Item}, TContext> => {

const mutationKey = ['updateItem'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, {universe: string;id: string;data: Item}> = (props) => {
          const {universe,id,data} = props ?? {};

          return  updateItem(universe,id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = Item
    export type UpdateItemMutationError = AxiosError<unknown>

    /**
 * @summary Updates an object in the database
 */
export const useUpdateItem = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{universe: string;id: string;data: Item}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        {universe: string;id: string;data: Item},
        TContext
      > => {

      const mutationOptions = getUpdateItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    